name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: ⬇️ Checkout Code
          uses: actions/checkout@v4

        - name: 🐢 Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: '22'

        - name: 🏗️ Install Dependencies
          run: npm install --force

        - name: 🧪 Test
          run: npm run wdio:android:bs

        - name: 📦 Upload Logs
          uses: actions/upload-artifact@v4
          if: failure()
          with:
            name: logs
            path: logs
